Merge 1.0 into 1.x (#2853)
* Fix many queries to storage for get files info

Previously, for each file there were 3 requests, now one request for all files

* TimeHandler

* Add translateable strings to database seeders

* adding browse_bread translation - RU

missing russian translation for __('voyager.database.browse_bread')

* Apply fixes from StyleCI

[ci skip] [skip ci]

* Fix: Undefined property AuthManager::$user

ErrorException: Undefined property: Illuminate\Auth\AuthManager::$user

* Fix Dropdowns not working with asian strings (#2798)

* Use max-width to avoid upscale (#2806)

* Multiple images fields show full size images on edit-form (#2803)

* Multiple images fields show full size images on edit-form

I notice that the "preview" images in edit-add form related to multi upload show images with the original sizes, then If we upload large photos form become unusable. I add some style to img and a float left to div container. I know that it's better to add a class in app.css but many formfields have inline css then for now I use the same method.

* change with width max-width

* Adding legend option to edit-create blade (#2804)

* Adding legend option to edit-create blade

you can add a new custom data field to define a legend:
    "legend": {
        "text": "Area File",
        "bgcolor": "#f0f0f0",
        "align": "center"
    }

* check first if isset($options->legend)

* Update edit-add.blade.php

* Wrong fields alignemnt (padding) in create/edit form (#2797)

* Wrong fields alignemnt (padding) in create/edit form 

if you not pass "col-md-12" if there are some custom display in other fields you have wrong alignment

* Update edit-add.blade.php

* Update edit-add.blade.php

* Update edit-add.blade.php

* Update edit-add.blade.php

* Add missing Chinese translations (#2838)

* Add Finnish translations, minor fixes to English translation (#2843)

* Bugfix

* Bugfix 2

* Add seeder-strings

* Merge remote-tracking branch 'upstream/1.x-dev' into merging-10-to-11